/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace AIBOMRegistry {
  export type AdvisoryStruct = {
    cid: PromiseOrValue<string>;
    scope: PromiseOrValue<string>;
    action: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    reporter: PromiseOrValue<string>;
  };

  export type AdvisoryStructOutput = [
    string,
    string,
    string,
    BigNumber,
    string
  ] & {
    cid: string;
    scope: string;
    action: string;
    timestamp: BigNumber;
    reporter: string;
  };

  export type AIBOMStruct = {
    owner: PromiseOrValue<string>;
    cid: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
    reviewReason: PromiseOrValue<string>;
  };

  export type AIBOMStructOutput = [
    string,
    string,
    BigNumber,
    number,
    string
  ] & {
    owner: string;
    cid: string;
    timestamp: BigNumber;
    status: number;
    reviewReason: string;
  };

  export type RegulatoryDossierStruct = {
    cid: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    description: PromiseOrValue<string>;
  };

  export type RegulatoryDossierStructOutput = [string, BigNumber, string] & {
    cid: string;
    timestamp: BigNumber;
    description: string;
  };

  export type VulnerabilityStruct = {
    cid: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    severity: PromiseOrValue<string>;
    active: PromiseOrValue<boolean>;
  };

  export type VulnerabilityStructOutput = [
    string,
    BigNumber,
    string,
    boolean
  ] & { cid: string; timestamp: BigNumber; severity: string; active: boolean };
}

export interface AIBOMRegistryInterface extends utils.Interface {
  functions: {
    "addSupervisor(address)": FunctionFragment;
    "aiboms(uint256)": FunctionFragment;
    "getAdvisories(uint256)": FunctionFragment;
    "getAllAIBOMs()": FunctionFragment;
    "getApprovedSubmissions(uint256)": FunctionFragment;
    "getMySubmissions(uint256)": FunctionFragment;
    "getRegulatoryDossier(uint256)": FunctionFragment;
    "getVulnerabilities(uint256)": FunctionFragment;
    "nextModelId()": FunctionFragment;
    "owner()": FunctionFragment;
    "recordAdvisory(uint256,string,string,string)": FunctionFragment;
    "registerAIBOM(string)": FunctionFragment;
    "regulatoryDossiers(uint256)": FunctionFragment;
    "removeSupervisor(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reportVulnerability(uint256,string,string)": FunctionFragment;
    "setReviewStatus(uint256,uint8,string)": FunctionFragment;
    "submitRegulatoryDossier(uint256,string,string)": FunctionFragment;
    "supervisors(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "vulnerabilities(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addSupervisor"
      | "aiboms"
      | "getAdvisories"
      | "getAllAIBOMs"
      | "getApprovedSubmissions"
      | "getMySubmissions"
      | "getRegulatoryDossier"
      | "getVulnerabilities"
      | "nextModelId"
      | "owner"
      | "recordAdvisory"
      | "registerAIBOM"
      | "regulatoryDossiers"
      | "removeSupervisor"
      | "renounceOwnership"
      | "reportVulnerability"
      | "setReviewStatus"
      | "submitRegulatoryDossier"
      | "supervisors"
      | "transferOwnership"
      | "vulnerabilities"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addSupervisor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "aiboms",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdvisories",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAIBOMs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApprovedSubmissions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMySubmissions",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegulatoryDossier",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVulnerabilities",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "nextModelId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordAdvisory",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAIBOM",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "regulatoryDossiers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupervisor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportVulnerability",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setReviewStatus",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRegulatoryDossier",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supervisors",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "vulnerabilities",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSupervisor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aiboms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdvisories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAIBOMs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApprovedSubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMySubmissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegulatoryDossier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVulnerabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextModelId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordAdvisory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAIBOM",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regulatoryDossiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupervisor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportVulnerability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReviewStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRegulatoryDossier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supervisors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vulnerabilities",
    data: BytesLike
  ): Result;

  events: {
    "AIBOMRegistered(uint256,address,string)": EventFragment;
    "AdvisoryRecorded(uint256,string,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RegulatoryDossierSubmitted(uint256,string)": EventFragment;
    "ReviewStatusChanged(uint256,uint8,string)": EventFragment;
    "VulnerabilityReported(uint256,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AIBOMRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdvisoryRecorded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegulatoryDossierSubmitted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReviewStatusChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VulnerabilityReported"): EventFragment;
}

export interface AIBOMRegisteredEventObject {
  modelId: BigNumber;
  dev: string;
  cid: string;
}
export type AIBOMRegisteredEvent = TypedEvent<
  [BigNumber, string, string],
  AIBOMRegisteredEventObject
>;

export type AIBOMRegisteredEventFilter = TypedEventFilter<AIBOMRegisteredEvent>;

export interface AdvisoryRecordedEventObject {
  modelId: BigNumber;
  cid: string;
  reporter: string;
}
export type AdvisoryRecordedEvent = TypedEvent<
  [BigNumber, string, string],
  AdvisoryRecordedEventObject
>;

export type AdvisoryRecordedEventFilter =
  TypedEventFilter<AdvisoryRecordedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RegulatoryDossierSubmittedEventObject {
  modelId: BigNumber;
  cid: string;
}
export type RegulatoryDossierSubmittedEvent = TypedEvent<
  [BigNumber, string],
  RegulatoryDossierSubmittedEventObject
>;

export type RegulatoryDossierSubmittedEventFilter =
  TypedEventFilter<RegulatoryDossierSubmittedEvent>;

export interface ReviewStatusChangedEventObject {
  modelId: BigNumber;
  status: number;
  reason: string;
}
export type ReviewStatusChangedEvent = TypedEvent<
  [BigNumber, number, string],
  ReviewStatusChangedEventObject
>;

export type ReviewStatusChangedEventFilter =
  TypedEventFilter<ReviewStatusChangedEvent>;

export interface VulnerabilityReportedEventObject {
  modelId: BigNumber;
  cid: string;
  severity: string;
}
export type VulnerabilityReportedEvent = TypedEvent<
  [BigNumber, string, string],
  VulnerabilityReportedEventObject
>;

export type VulnerabilityReportedEventFilter =
  TypedEventFilter<VulnerabilityReportedEvent>;

export interface AIBOMRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AIBOMRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addSupervisor(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    aiboms(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, number, string] & {
        owner: string;
        cid: string;
        timestamp: BigNumber;
        status: number;
        reviewReason: string;
      }
    >;

    getAdvisories(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AIBOMRegistry.AdvisoryStructOutput[]]>;

    getAllAIBOMs(
      overrides?: CallOverrides
    ): Promise<[AIBOMRegistry.AIBOMStructOutput[]]>;

    getApprovedSubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getMySubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AIBOMRegistry.RegulatoryDossierStructOutput]>;

    getVulnerabilities(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AIBOMRegistry.VulnerabilityStructOutput[]]>;

    nextModelId(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    recordAdvisory(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      scope: PromiseOrValue<string>,
      action: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerAIBOM(
      cid: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    regulatoryDossiers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        cid: string;
        timestamp: BigNumber;
        description: string;
      }
    >;

    removeSupervisor(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reportVulnerability(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      severity: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setReviewStatus(
      modelId: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    submitRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      desc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supervisors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vulnerabilities(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean] & {
        cid: string;
        timestamp: BigNumber;
        severity: string;
        active: boolean;
      }
    >;
  };

  addSupervisor(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  aiboms(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, number, string] & {
      owner: string;
      cid: string;
      timestamp: BigNumber;
      status: number;
      reviewReason: string;
    }
  >;

  getAdvisories(
    modelId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AIBOMRegistry.AdvisoryStructOutput[]>;

  getAllAIBOMs(
    overrides?: CallOverrides
  ): Promise<AIBOMRegistry.AIBOMStructOutput[]>;

  getApprovedSubmissions(
    modelId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getMySubmissions(
    modelId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRegulatoryDossier(
    modelId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AIBOMRegistry.RegulatoryDossierStructOutput>;

  getVulnerabilities(
    modelId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AIBOMRegistry.VulnerabilityStructOutput[]>;

  nextModelId(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  recordAdvisory(
    modelId: PromiseOrValue<BigNumberish>,
    cid: PromiseOrValue<string>,
    scope: PromiseOrValue<string>,
    action: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerAIBOM(
    cid: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  regulatoryDossiers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string] & {
      cid: string;
      timestamp: BigNumber;
      description: string;
    }
  >;

  removeSupervisor(
    who: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reportVulnerability(
    modelId: PromiseOrValue<BigNumberish>,
    cid: PromiseOrValue<string>,
    severity: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setReviewStatus(
    modelId: PromiseOrValue<BigNumberish>,
    status: PromiseOrValue<BigNumberish>,
    reason: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  submitRegulatoryDossier(
    modelId: PromiseOrValue<BigNumberish>,
    cid: PromiseOrValue<string>,
    desc: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supervisors(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vulnerabilities(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, string, boolean] & {
      cid: string;
      timestamp: BigNumber;
      severity: string;
      active: boolean;
    }
  >;

  callStatic: {
    addSupervisor(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    aiboms(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, number, string] & {
        owner: string;
        cid: string;
        timestamp: BigNumber;
        status: number;
        reviewReason: string;
      }
    >;

    getAdvisories(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AIBOMRegistry.AdvisoryStructOutput[]>;

    getAllAIBOMs(
      overrides?: CallOverrides
    ): Promise<AIBOMRegistry.AIBOMStructOutput[]>;

    getApprovedSubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getMySubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AIBOMRegistry.RegulatoryDossierStructOutput>;

    getVulnerabilities(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AIBOMRegistry.VulnerabilityStructOutput[]>;

    nextModelId(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    recordAdvisory(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      scope: PromiseOrValue<string>,
      action: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerAIBOM(
      cid: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    regulatoryDossiers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string] & {
        cid: string;
        timestamp: BigNumber;
        description: string;
      }
    >;

    removeSupervisor(
      who: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    reportVulnerability(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      severity: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setReviewStatus(
      modelId: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    submitRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      desc: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supervisors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    vulnerabilities(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, string, boolean] & {
        cid: string;
        timestamp: BigNumber;
        severity: string;
        active: boolean;
      }
    >;
  };

  filters: {
    "AIBOMRegistered(uint256,address,string)"(
      modelId?: PromiseOrValue<BigNumberish> | null,
      dev?: PromiseOrValue<string> | null,
      cid?: null
    ): AIBOMRegisteredEventFilter;
    AIBOMRegistered(
      modelId?: PromiseOrValue<BigNumberish> | null,
      dev?: PromiseOrValue<string> | null,
      cid?: null
    ): AIBOMRegisteredEventFilter;

    "AdvisoryRecorded(uint256,string,address)"(
      modelId?: PromiseOrValue<BigNumberish> | null,
      cid?: null,
      reporter?: null
    ): AdvisoryRecordedEventFilter;
    AdvisoryRecorded(
      modelId?: PromiseOrValue<BigNumberish> | null,
      cid?: null,
      reporter?: null
    ): AdvisoryRecordedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RegulatoryDossierSubmitted(uint256,string)"(
      modelId?: PromiseOrValue<BigNumberish> | null,
      cid?: null
    ): RegulatoryDossierSubmittedEventFilter;
    RegulatoryDossierSubmitted(
      modelId?: PromiseOrValue<BigNumberish> | null,
      cid?: null
    ): RegulatoryDossierSubmittedEventFilter;

    "ReviewStatusChanged(uint256,uint8,string)"(
      modelId?: PromiseOrValue<BigNumberish> | null,
      status?: null,
      reason?: null
    ): ReviewStatusChangedEventFilter;
    ReviewStatusChanged(
      modelId?: PromiseOrValue<BigNumberish> | null,
      status?: null,
      reason?: null
    ): ReviewStatusChangedEventFilter;

    "VulnerabilityReported(uint256,string,string)"(
      modelId?: PromiseOrValue<BigNumberish> | null,
      cid?: null,
      severity?: null
    ): VulnerabilityReportedEventFilter;
    VulnerabilityReported(
      modelId?: PromiseOrValue<BigNumberish> | null,
      cid?: null,
      severity?: null
    ): VulnerabilityReportedEventFilter;
  };

  estimateGas: {
    addSupervisor(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    aiboms(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAdvisories(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllAIBOMs(overrides?: CallOverrides): Promise<BigNumber>;

    getApprovedSubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMySubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVulnerabilities(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextModelId(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    recordAdvisory(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      scope: PromiseOrValue<string>,
      action: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerAIBOM(
      cid: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    regulatoryDossiers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeSupervisor(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reportVulnerability(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      severity: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setReviewStatus(
      modelId: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    submitRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      desc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supervisors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vulnerabilities(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addSupervisor(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    aiboms(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAdvisories(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllAIBOMs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getApprovedSubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMySubmissions(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVulnerabilities(
      modelId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextModelId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recordAdvisory(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      scope: PromiseOrValue<string>,
      action: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerAIBOM(
      cid: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    regulatoryDossiers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeSupervisor(
      who: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reportVulnerability(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      severity: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setReviewStatus(
      modelId: PromiseOrValue<BigNumberish>,
      status: PromiseOrValue<BigNumberish>,
      reason: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    submitRegulatoryDossier(
      modelId: PromiseOrValue<BigNumberish>,
      cid: PromiseOrValue<string>,
      desc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supervisors(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vulnerabilities(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
